"""Sync ESGRating naming and constraints

Revision ID: 2961421f6271
Revises: aaf8e7b6e4fd
Create Date: 2026-03-05 19:26:21.307712

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2961421f6271'
down_revision: Union[str, Sequence[str], None] = 'aaf8e7b6e4fd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Manual Fix: Rename column instead of Add/Drop to preserve existing data
    op.alter_column('esg_rating', 'ticker', new_column_name='ticker_symbol')
    
    op.drop_constraint(op.f('esg_rating_ticker_key'), 'esg_rating', type_='unique')
    op.create_unique_constraint(None, 'esg_rating', ['ticker_symbol'])
    
    op.drop_constraint(op.f('esg_rating_ticker_fkey'), 'esg_rating', type_='foreignkey')
    op.create_foreign_key(None, 'esg_rating', 'ticker', ['ticker_symbol'], ['symbol'])
    
    op.create_unique_constraint(None, 'investment_rule', ['account_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'investment_rule', type_='unique')
    
    # Manual Fix: Rename column back
    op.alter_column('esg_rating', 'ticker_symbol', new_column_name='ticker')
    
    op.drop_constraint(None, 'esg_rating', type_='foreignkey')
    op.create_foreign_key(op.f('esg_rating_ticker_fkey'), 'esg_rating', 'ticker', ['ticker'], ['symbol'])
    
    op.drop_constraint(None, 'esg_rating', type_='unique')
    op.create_unique_constraint(op.f('esg_rating_ticker_key'), 'esg_rating', ['ticker'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
