"""Refine ESGRating uniqueness and add Account balance tracking

Revision ID: aaf8e7b6e4fd
Revises: 80b296908c18
Create Date: 2026-03-04 00:33:37.941702

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aaf8e7b6e4fd'
down_revision: Union[str, Sequence[str], None] = '80b296908c18'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'esg_rating', ['ticker'])
    op.add_column('portfolio_holding', sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False))
    op.drop_column('portfolio_holding', 'quantity')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('portfolio_holding', sa.Column('quantity', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=False))
    op.drop_column('portfolio_holding', 'amount')
    op.drop_constraint(None, 'esg_rating', type_='unique')
    # ### end Alembic commands ###
